title: <p align="center"> Kim-Cuong Nguyen </p>

logo: "/images/image.PNG?raw=true"

description:
  <p align="center">
  <a href="mailto:kn528@dragons.drexel.edu">Email</a> |
  <a href="/resume">Resume</a> |
  <a href="https://www.linkedin.com/in/ntkcuong/">LinkedIn</a> |
  <a href="https://github.com/kcngnn">GitHub</a>
  </p>
  
  <p align="justify">
  I graduated from Drexel University with a Master's in Business Analytics in March 2021.
  <br><br>
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-177299490-1 # your Google Analytics tracking ID here
